### ISSUE TITLE
Cantaloupe writing to log file error

### ISSUE THREAD

**Issue by Tristaan** [Islandora-Devops/isle-buildkit#144]
Hello, there seems to be a permission problem with tomcat inside the cantaloupe container. This throws an error:
```
cantaloupe_1  | 07:21:17,856 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[AccessRollingFileLog] - openFile(_opt_tomcat_logs_cantaloupe.access.log,true) call failed. java.io.FileNotFoundException: _opt_tomcat_logs_cantaloupe.access.log (Permission denied)
cantaloupe_1  | 	at java.io.FileNotFoundException: _opt_tomcat_logs_cantaloupe.access.log (Permission denied)
cantaloupe_1  | 	at 	at java.io.FileOutputStream.open0(Native Method)
...
```
So this has to do something with the file not existing, because it doesn't. If you replace the underscores with slashes the file exists. So now I am not sure if it doesn't use the correct file or if there really is a permission problem. Logging works as it seems but some parts of the logs are omitted, if I assume correctly.

**Comment by scottdoane** [comment]
Seeing this issue as well on both local workstation, and server. 

**Workstation**: OS X running Rancher Desktop w/Kubernetes 1.20.6
**Server**: Kubernetes 1.20.6 w/Docker 20.10.9

Both workstation and server deployment spaces are operating without pod security policies, so there are no restrictions on operating procedures. In both environment the image is running as the default root user. 

The most minimal deployment, either locally or on server, produces the error. Can repeat it locally with the following:

`docker run -it --rm islandora/cantaloupe:1.0.0-alpha-10`

Startup log below: 

```
...
14:36:45,932 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[AppRollingFileLog] - Active log file name: _opt_tomcat_logs_cantaloupe.application.log
14:36:45,932 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[AppRollingFileLog] - File property is set to [_opt_tomcat_logs_cantaloupe.application.log]
14:36:45,933 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[AppRollingFileLog] - openFile(_opt_tomcat_logs_cantaloupe.application.log,true) call failed. java.io.FileNotFoundException: _opt_tomcat_logs_cantaloupe.application.log (Permission denied)
	at java.io.FileNotFoundException: _opt_tomcat_logs_cantaloupe.application.log (Permission denied)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
...
```

It appears to be a permissions quirk in the way the symlink is being instantiated: 


By default the tomcat user is unable to write to the symlink. 
```
bash-5.1# stat -L logs/cantaloupe.access.log
  File: logs/cantaloupe.access.log
  Size: 0         	Blocks: 0          IO Block: 1024   character special file
Device: 58h/88d	Inode: 4           Links: 1     Device type: 88,1
Access: (0620/crw--w----)  Uid: (    0/    root)   Gid: (    5/     tty)
Access: 2021-11-17 14:49:52.019995789 +0000
Modify: 2021-11-17 14:49:52.019995789 +0000
Change: 2021-11-17 14:49:38.039995788 +0000
bash-5.1# su - tomcat -s /bin/bash
394f83518180:~$ echo "test as tomcat user" >> logs/cantaloupe.access.log
-bash: logs/cantaloupe.access.log: Permission denied
```

By forcing the permissions, the user can write.
```
bash-5.1# stat -L logs/cantaloupe.access.log
  File: logs/cantaloupe.access.log
  Size: 0         	Blocks: 0          IO Block: 1024   character special file
Device: 58h/88d	Inode: 4           Links: 1     Device type: 88,1
Access: (0620/crw--w----)  Uid: (    0/    root)   Gid: (    5/     tty)
Access: 2021-11-17 14:49:52.019995789 +0000
Modify: 2021-11-17 14:49:52.019995789 +0000
Change: 2021-11-17 14:49:38.039995788 +0000
bash-5.1# su - tomcat -s /bin/bash
394f83518180:~$ echo "test as tomcat user" >> logs/cantaloupe.access.log
-bash: logs/cantaloupe.access.log: Permission denied
394f83518180:~$ exit
logout
bash-5.1# chown tomcat:tomcat logs/cantaloupe.*
bash-5.1# stat -L logs/cantaloupe.access.log
  File: logs/cantaloupe.access.log
  Size: 0         	Blocks: 0          IO Block: 1024   character special file
Device: 58h/88d	Inode: 4           Links: 1     Device type: 88,1
Access: (0620/crw--w----)  Uid: (  100/  tomcat)   Gid: ( 1000/  tomcat)
Access: 2021-11-17 14:51:53.019995789 +0000
Modify: 2021-11-17 14:51:53.019995789 +0000
Change: 2021-11-17 14:51:49.039995128 +0000
bash-5.1# su - tomcat -s /bin/bash
394f83518180:~$ echo "test as tomcat user" >> logs/cantaloupe.access.log
test as tomcat user
```

This isn't a workable solution, provides illustration of an underlying cause.

**Comment by scottdoane** [comment]
On further review, it appears that 02-cantoloupe-install.sh is not being applied properly during the init sequence. The logging indicates that it runs and exits cleanly, but permissions remain incorrect on the symlinks. 

```
[~][glib:isle-dev]$ docker run -it --rm islandora/cantaloupe:1.0.0-alpha-10                                                                  [2021-11-17 8:36:30]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-container-environment-00-init.sh: executing...
[cont-init.d] 00-container-environment-00-init.sh: exited 0.
[cont-init.d] 00-container-environment-01-override-tomcat.sh: executing...
[cont-init.d] 00-container-environment-01-override-tomcat.sh: exited 0.
[cont-init.d] 00-container-environment-02-database-defaults.sh: executing...
[cont-init.d] 00-container-environment-02-database-defaults.sh: exited 0.
[cont-init.d] 01-confd-render-templates.sh: executing...
[cont-init.d] 01-confd-render-templates.sh: exited 0.
[cont-init.d] 02-cantoloupe-install.sh: executing...
[cont-init.d] 02-cantoloupe-install.sh: exited 0.
[cont-init.d] 02-ngnix-install.sh: executing...
[cont-init.d] 02-ngnix-install.sh: exited 0.
[cont-init.d] done.
```

**Comment by nigelgbanks** [comment]
Looks like the only proper solution going forward is to use Tomcats logging configuration such that it writes to standard out/error rather than relying on symlinks. Hopefully all the files written to by the various tomcat wars use Tomcats logging facilities and just don't write directly to the files themselves.

**Comment by nigelgbanks** [comment]
https://cantaloupe-project.github.io/manual/4.1/logging.html

**Comment by nigelgbanks** [comment]
So `/opt/tomcat/webapps/cantaloupe/WEB-INF/classes/logback.xml` is how all the logging is configured by Cantaloupe. The configuration of this is driven by the values set in `/opt/tomcat/conf/cantaloupe.properties` which we derive from environment variables [here](https://github.com/Islandora-Devops/isle-buildkit/blob/main/cantaloupe/Dockerfile#L35). The default settings should just disable all file output and only use standard out / error. Then we can get rid of those symlinks as well.

**Comment by nigelgbanks** [comment]
@Tristaan and @scottdoane I've raised a pull request that fixes the issue: https://github.com/Islandora-Devops/isle-buildkit/pull/165. 

I can't tag either of you on the pull request for review since your not in the committers group I think, but if you leave a comment on the pull that it works for you then I'll merge it.
